Ransom = ["Who says nothing is impossible? I've been doing nothing for years.",
        "Never take life seriously. Nobody gets out alive anyway.",
        "If you die in an elevator, be sure to push the Up button.",
        "Love your enemies. It makes them so damned mad.",
        "Never let a fool kiss you, or a kiss fool you.",
        "Never test how deep the water is with both feet.",
        "For the best seat in the house, you'll have to move the dog.",
        "It's not important to win, it's important to make the other guy lose.",
        "He who laughs last didn't get it.",
        "Friends buy you food. Best friends eat your food.",
        "Sometimes when I close my eyes, I can't see.",
        "Roses are red, my name is not Dave, this makes no sense, microwave.",
        "When you fall, I will be there to catch you - With love, the floor.",
        "Maybe if we tell people the brain is an app, they'll start using it.",
        "I am on a seafood diet. I see food, and I eat it.",
        "Life's biggest struggle: I need to pee, but I don't want to get out of bed.",
        "Don't be stupid, it might make you famous.",
        "If you think nothing is impossible, try slamming a revolving door.",
        "My wallet is like an onion, opening it makes me cry.",
        "When nothing is going right, go left.",
        "Fart when someone hugs you, it makes them feel strong.",
        "Minds are like Parachutes. They work best when open.",
        "Why do farts smell? For benefit of the deaf.",
        '''A sandwich walks into a bar. The barman says "Sorry we don't serve food in here"''',
        "ALGEBRA: A weapon of math destruction.",
        "As a computer, I find your faith in technology amusing",
        "Born Free. . . . .Taxed to Death.",
        "Hard work has a future payoff. Laziness pays off NOW!",
        "I get enough exercise just pushing my luck!",
        "I took an IQ test and the results were negative."]
