# Generated by Django 3.0.3 on 2020-02-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(blank=True, max_length=20)),
                ('y', models.CharField(blank=True, max_length=20)),
                ('result', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
