# Generated by Django 3.0.3 on 2020-02-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20200224_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='x',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='calc',
            name='y',
            field=models.FloatField(blank=True),
        ),
    ]
